### ISSUE TITLE
Not all conditions can be seen and chosen

### ISSUE THREAD

**Issue by aartiomov** [VirtoCommerce/vc-module-dynamic-expressions#3]
When the expressions block is in the bottom of the screen and you want to add condition not all options are seen. Those can be viewed only when you zoom out. It should allow to scroll down the blade or display options not to the bottom of the mouse pointer but to the top, if not all menu items fits into the view. Like windows context menus does. See screencast below.
![image](http://g.recordit.co/mTIwhpSjqO.gif)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.33
