### ISSUE TITLE
IsItemCodeContains logic issue

### ISSUE THREAD

**Issue by ArvidBauters** [VirtoCommerce/vc-module-dynamic-expressions#8]
Hi,

it seems that the implementation of IsItemCodeContains is a bit off. 

current implementation is:
        public static bool IsItemCodeContains(this PromotionEvaluationContext context, string code)
        {
            return new ProductPromoEntry[] { context.PromoEntry }.Where(x => String.Equals(code, x.Code, StringComparison.InvariantCultureIgnoreCase)).Any();

        }

I would expect the return statement to be using the Contains method instead of the Equals method. So something like this:
return new ProductPromoEntry[] { context.PromoEntry }.Any(x=>x.Code.Contains(code));

**Comment by ArvidBauters** [comment]
Ok, will there be a new version be created with this bugfix?

**Comment by tatarincev** [comment]
Sure. Do you want it now?

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-dynamic-expressions/releases/tag/v2.13.1
